spring:
  application:
    name: Expense Splitter App
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: expenseSplitterDb
      #it will automatically create indexes in document fields:
      auto-index-creation: true
  main:
    allow-circular-references: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB


exchange-rate-getter:
  api:
    key: ${ERG_API_KEY}

reactjs-frontend:
  origin: ${REACTJS_FRONTEND_ORIGIN}

cloudinary:
  cloud_name: ${CLOUDINARY_CLOUD_NAME}
  api_key: ${CLOUDINARY_API_KEY}
  api_secret: ${CLOUDINARY_API_SECRET}

admin-empids: ${ADMIN_EMPIDS}